
    create table attendance (
        attendance_date date not null,
        created_date date not null,
        id bigint generated by default as identity,
        student_id bigint not null,
        teacher_id bigint not null,
        session enum ('AN','EN','FN') not null,
        status enum ('A','OD','P') not null,
        primary key (id),
        unique (student_id, attendance_date, session),
        check (session IN ('FN','AN','EN') AND status IN ('P','A','OD'))
    );

    create table attendance_unlocks (
        date date not null,
        unlocked boolean not null,
        id bigint generated by default as identity,
        updated_time timestamp(6),
        updated_by varchar(100),
        session enum ('AN','EN','FN') not null,
        primary key (id),
        unique (date, session)
    );

    create table audit_logs (
        id bigint generated by default as identity,
        timestamp timestamp(6) not null,
        device_type varchar(20),
        ip_address varchar(45),
        role varchar(50),
        user_id varchar(100),
        user_email varchar(150) not null,
        action varchar(200) not null,
        entity_name varchar(200),
        primary key (id)
    );

    create table batches (
        active boolean not null,
        id bigint generated by default as identity,
        batch_name varchar(50) not null unique,
        primary key (id)
    );

    create table departments (
        active boolean not null,
        id bigint generated by default as identity,
        department_name varchar(50) not null unique,
        primary key (id)
    );

    create table sections (
        active boolean not null,
        created_at timestamp(6) not null,
        department_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        section_name varchar(255) not null,
        primary key (id),
        constraint uk_section_name_dept unique (section_name, department_id)
    );

    create table students (
        academic_year integer not null,
        active boolean not null,
        evening_class boolean not null,
        evening_class_enabled boolean not null,
        hosteller boolean not null,
        batch_id bigint not null,
        created_at timestamp(6) not null,
        department_id bigint not null,
        id bigint generated by default as identity,
        section_id bigint,
        updated_at timestamp(6) not null,
        register_number varchar(50) not null unique,
        student_name varchar(255) not null,
        primary key (id)
    );

    create table teachers (
        active boolean not null,
        id bigint generated by default as identity,
        user_id bigint not null unique,
        access_type varchar(50),
        employee_id varchar(50) not null unique,
        designation varchar(100),
        email varchar(100),
        full_name varchar(100),
        primary key (id)
    );

    create table users (
        active boolean not null,
        failed_login_attempts integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        lockout_time timestamp(6),
        updated_at timestamp(6) not null,
        email varchar(100),
        user_id varchar(100) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role enum ('ADMIN','TEACHER') not null,
        primary key (id)
    );

    create index idx_student_date 
       on attendance (student_id, attendance_date);

    create index idx_teacher 
       on attendance (teacher_id);

    create index idx_attendance_date 
       on attendance (attendance_date);

    create index idx_attendance_session 
       on attendance (session);

    create index idx_register_number 
       on students (register_number);

    create index idx_student_dept 
       on students (department_id);

    create index idx_student_batch 
       on students (batch_id);

    create index idx_teacher_employee 
       on teachers (employee_id);

    create index idx_user_id 
       on users (user_id);

    alter table if exists attendance 
       add constraint FKgjm8wg1wx3eny9wvw0jholvsy 
       foreign key (teacher_id) 
       references teachers;

    alter table if exists attendance 
       add constraint FK7121lveuhtmu9wa6m90ayd5yg 
       foreign key (student_id) 
       references students;

    alter table if exists sections 
       add constraint FKgnisg480cbsx8krnlq30qaym5 
       foreign key (department_id) 
       references departments;

    alter table if exists students 
       add constraint FKdq4ek4hqr0unqrf0opvl6yneh 
       foreign key (batch_id) 
       references batches;

    alter table if exists students 
       add constraint FKalgc33nsolpmegw14o3h6g6rr 
       foreign key (department_id) 
       references departments;

    alter table if exists students 
       add constraint FKbu72kq4xd8qjcemytgfxel71l 
       foreign key (section_id) 
       references sections;

    alter table if exists teachers 
       add constraint FKb8dct7w2j1vl1r2bpstw5isc0 
       foreign key (user_id) 
       references users;
