CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255) NOT NULL,
    user_id VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    lockout_time TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_user_id ON users(user_id);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_name VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    section_name VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_section_name_dept UNIQUE (section_name, department_id),
    CONSTRAINT fk_sections_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    student_name VARCHAR(255) NOT NULL,
    hosteller BOOLEAN NOT NULL DEFAULT FALSE,
    register_number VARCHAR(50) NOT NULL UNIQUE,
    department_id BIGINT NOT NULL,
    academic_year INTEGER NOT NULL,
    batch_id BIGINT NOT NULL,
    section_id BIGINT,
    evening_class_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_students_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_students_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
    CONSTRAINT fk_students_section FOREIGN KEY (section_id) REFERENCES sections(id)
);
CREATE INDEX IF NOT EXISTS idx_register_number ON students(register_number);
CREATE INDEX IF NOT EXISTS idx_student_dept ON students(department_id);
CREATE INDEX IF NOT EXISTS idx_student_batch ON students(batch_id);

CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL UNIQUE,
    employee_id VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100),
    email VARCHAR(100),
    access_type VARCHAR(50),
    designation VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT fk_teachers_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_teacher_employee ON teachers(employee_id);

CREATE TABLE IF NOT EXISTS attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id VARCHAR(255) NOT NULL UNIQUE,
    subject_id BIGINT,
    teacher_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    session_name VARCHAR(255),
    is_active BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_session_status ON attendance_sessions(status);
CREATE INDEX IF NOT EXISTS idx_session_teacher ON attendance_sessions(teacher_id);

CREATE TABLE IF NOT EXISTS attendance_unlocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL,
    session VARCHAR(20) NOT NULL,
    unlocked BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by VARCHAR(100),
    updated_time TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_attendance_unlocks_date_session UNIQUE (date, session)
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attendance_date DATE NOT NULL,
    session VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    student_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    created_date DATE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_attendance_student_date_session UNIQUE (student_id, attendance_date, session),
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_attendance_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    CONSTRAINT chk_attendance_session_status CHECK (session IN ('FN','AN','EN') AND status IN ('P','A','OD'))
);
CREATE INDEX IF NOT EXISTS idx_student_date ON attendance(student_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_teacher ON attendance(teacher_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_session ON attendance(session);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_email VARCHAR(150) NOT NULL,
    user_id VARCHAR(100),
    action VARCHAR(200) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    ip_address VARCHAR(45),
    role VARCHAR(50),
    entity_name VARCHAR(200),
    device_type VARCHAR(20),
    PRIMARY KEY (id)
);
