-- V2: two-role model, registration-number domain model, CSV import support.
-- Every change here is additive or a safe data update - nothing destructive, no data loss,
-- no existing row is deleted. Unique constraints on new columns are partial (WHERE ... IS NOT
-- NULL) so existing rows that don't have a value yet are never blocked or forced.

-- ---------------------------------------------------------------------------
-- 1. Role model: SUPER_ADMIN -> ADMIN, ATTENDANCE_MANAGER -> TEACHER.
--    Decision record: ATTENDANCE_MANAGER is mapped to TEACHER, not ADMIN, because it was never
--    granted any admin-only endpoint in SecurityConfig (only /api/teacher/**, /api/attendance/**,
--    and read-only department/batch lookups - identical to TEACHER), and the frontend's own
--    post-login redirect already routed ATTENDANCE_MANAGER to the teacher dashboard.
--    audit_logs.role is intentionally left untouched - historical records keep the role name
--    that was actually in effect at the time of the logged action.
-- ---------------------------------------------------------------------------
UPDATE users SET role = 'ADMIN' WHERE role = 'SUPER_ADMIN';
UPDATE users SET role = 'TEACHER' WHERE role = 'ATTENDANCE_MANAGER';

-- ---------------------------------------------------------------------------
-- 2. Department code (digits 7-9 of a registration number resolve to this).
-- ---------------------------------------------------------------------------
ALTER TABLE departments ADD COLUMN IF NOT EXISTS department_code VARCHAR(10);
CREATE UNIQUE INDEX IF NOT EXISTS uk_department_code ON departments(department_code) WHERE department_code IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3. Batch becomes structured data: department + start/end year, instead of a bare global name.
-- ---------------------------------------------------------------------------
ALTER TABLE batches ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES departments(id);
ALTER TABLE batches ADD COLUMN IF NOT EXISTS start_year INTEGER;
ALTER TABLE batches ADD COLUMN IF NOT EXISTS end_year INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS uk_batch_dept_years ON batches(department_id, start_year, end_year)
    WHERE department_id IS NOT NULL AND start_year IS NOT NULL AND end_year IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 4. Teacher department assignment (fixes the departmentId=null scoping gap).
-- ---------------------------------------------------------------------------
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES departments(id);
CREATE INDEX IF NOT EXISTS idx_teacher_department ON teachers(department_id);

-- ---------------------------------------------------------------------------
-- 5. Point-in-time department/batch snapshot on attendance, so a later batch/department
--    correction never silently rewrites which class historical attendance appears under.
--    Nullable and only populated going forward - existing historical rows are left as-is
--    rather than guessed at, since backfilling them would mean inventing history.
-- ---------------------------------------------------------------------------
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES departments(id);
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS batch_id BIGINT REFERENCES batches(id);

-- ---------------------------------------------------------------------------
-- 6. CSV import tracking, for idempotent re-import and a real "Import Complete" summary.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS csv_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_hash VARCHAR(64) NOT NULL,
    imported_by VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    new_students INTEGER NOT NULL DEFAULT 0,
    updated_students INTEGER NOT NULL DEFAULT 0,
    unchanged_students INTEGER NOT NULL DEFAULT 0,
    new_departments INTEGER NOT NULL DEFAULT 0,
    new_batches INTEGER NOT NULL DEFAULT 0,
    error_rows INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_csv_import_hash ON csv_imports(file_hash);
CREATE INDEX IF NOT EXISTS idx_csv_import_status ON csv_imports(status);

-- ---------------------------------------------------------------------------
-- 7. Session-unlock reason (Admin unlock currently records nothing about why).
-- ---------------------------------------------------------------------------
ALTER TABLE attendance_unlocks ADD COLUMN IF NOT EXISTS reason VARCHAR(500);
